//! SQLite's case-insensitive string comparisons — `sqlite3StrICmp` and
//! `sqlite3StrNICmp`, the engine's own `stricmp` (retailOS has no ADS
//! `strcmp`, see ipod-decomp's AGENTS.md).
//!
//! - `str_icmp` — original: `FUN_08384f14` @ 0x08384f14 (72 bytes;
//!   **70 `bl` call sites**, binary-scanned).
//! - `str_nicmp` — original: `FUN_08384fa0` @ 0x08384fa0 (96 bytes;
//!   19 `bl` + 1 tail `b`).
//!
//! Both fold each byte through a 256-entry map before comparing, and
//! return the *difference of the folded bytes* at the first mismatch —
//! not a normalized -1/0/1. Neither is NUL-symmetric: only the left
//! string's terminator stops the loop, so the right string is read one
//! byte past its own NUL when it is the shorter one (harmless — that byte
//! is the NUL that ends the comparison anyway).
//!
//! ### Where the fold table comes from
//!
//! Both functions load the literal 0x088faa8b and index it. Reading the
//! decrypted image at 0x088faa8b gives unrelated bytes (a 12-byte-record
//! string index) in which `table['A'] != table['a']`, which is why this
//! pair was previously left unported. That reading is wrong: above the
//! read-only image the decrypted body's addresses are skewed by 0xaed8,
//! and the datum lives at image address 0x08905963. There it is
//! `sqlite3UpperToLower` byte-for-byte — the identity map except
//! `'A'..='Z'` -> `'a'..='z'` — and that byte sequence occurs exactly
//! once in the whole 10 MB image and is named by no pointer literal, i.e.
//! it is precisely the initializer for the address these functions use.
//! The skew is confirmed independently by the pool alignment table
//! (0x089cb1bc + 0xaed8 = 0x089d6094, the bytes `heap/pool.rs` documents)
//! and by every pointer literal into 0x088e0000..0x08920000 resolving to
//! a readable C string only at +0xaed8. See `sqlite/mod.rs`.
//!
//! Three functions share the table: these two plus the no-case hash
//! @ 0x08391df0 (`h = (h<<3) ^ h ^ table[*z++]`, SQLite's `strHash` for
//! `SQLITE_HASH_NOCASE`) — which is outside this sweep's range.
//!
//! Deviation: none. The map is reproduced as a table, generated by the
//! same rule the original's data was, and the comparison is byte-exact.

/// `sqlite3UpperToLower` @ runtime 0x088faa8b (image 0x08905963): the
/// identity map with the 26 ASCII uppercase letters folded down. It is
/// *only* ASCII — bytes 0x80..=0xff pass through unchanged, so no
/// locale or Latin-1 folding happens here.
pub static UPPER_TO_LOWER: [u8; 256] = build_upper_to_lower();

const fn build_upper_to_lower() -> [u8; 256] {
    let mut table = [0u8; 256];
    let mut i = 0usize;
    while i < 256 {
        table[i] = if i >= b'A' as usize && i <= b'Z' as usize {
            (i + 0x20) as u8
        } else {
            i as u8
        };
        i += 1;
    }
    table
}

/// Folds one byte through [`UPPER_TO_LOWER`] (the original's
/// `ldrb rX, [table, rX]` — the index is a byte, so it is always in
/// range).
#[inline(always)]
fn fold(byte: u8) -> i32 {
    UPPER_TO_LOWER[byte as usize] as i32
}

/// str_icmp — original: `FUN_08384f14` @ 0x08384f14 (72 bytes;
/// 70 `bl` call sites).
///
/// `sqlite3StrICmp`: compare NUL-terminated `left` and `right`
/// case-insensitively. Returns `fold(*left) - fold(*right)` at the first
/// position where the folded bytes differ, or where `*left` is NUL.
#[cfg_attr(target_os = "none", no_mangle)]
#[inline(never)]
pub unsafe extern "C" fn str_icmp(left: *const u8, right: *const u8) -> i32 {
    let mut a = left;
    let mut b = right;
    loop {
        let byte = a.read_volatile();
        if byte == 0 || fold(byte) != fold(b.read_volatile()) {
            break;
        }
        a = a.add(1);
        b = b.add(1);
    }
    fold(a.read_volatile()) - fold(b.read_volatile())
}

/// str_nicmp — original: `FUN_08384fa0` @ 0x08384fa0 (96 bytes;
/// 19 `bl` + 1 tail `b`).
///
/// `sqlite3StrNICmp`: [`str_icmp`] over at most `n` bytes. Returns 0 when
/// the budget runs out with everything matched so far — including for
/// `n <= 0`, where nothing is read at all. Otherwise the same folded
/// difference as [`str_icmp`].
///
/// The original decrements `n` *before* testing it (`subs r3, r2, #0;
/// sub r2, r2, #1; ble ...`), so after the loop `n` is negative exactly
/// when the budget was exhausted, which is the condition it turns into a
/// 0 result. Reproduced literally.
#[cfg_attr(target_os = "none", no_mangle)]
#[inline(never)]
pub unsafe extern "C" fn str_nicmp(left: *const u8, right: *const u8, n: i32) -> i32 {
    let mut a = left;
    let mut b = right;
    let mut remaining = n;
    loop {
        let budget = remaining;
        remaining = remaining.wrapping_sub(1);
        if budget <= 0 {
            break;
        }
        let byte = a.read_volatile();
        if byte == 0 || fold(byte) != fold(b.read_volatile()) {
            break;
        }
        a = a.add(1);
        b = b.add(1);
    }
    if remaining < 0 {
        return 0;
    }
    fold(a.read_volatile()) - fold(b.read_volatile())
}

#[cfg(test)]
mod tests {
    extern crate std;
    use super::*;
    use std::vec::Vec;

    /// The reference: the map as SQLite documents it, spelled out
    /// independently of [`build_upper_to_lower`].
    fn reference_fold(byte: u8) -> i32 {
        match byte {
            b'A'..=b'Z' => (byte + 0x20) as i32,
            other => other as i32,
        }
    }

    fn reference_icmp(left: &[u8], right: &[u8]) -> i32 {
        let mut i = 0;
        while left[i] != 0 && reference_fold(left[i]) == reference_fold(right[i]) {
            i += 1;
        }
        reference_fold(left[i]) - reference_fold(right[i])
    }

    fn reference_nicmp(left: &[u8], right: &[u8], n: i32) -> i32 {
        let mut i = 0usize;
        let mut remaining = n;
        loop {
            let budget = remaining;
            remaining = remaining.wrapping_sub(1);
            if budget <= 0 {
                break;
            }
            if left[i] == 0 || reference_fold(left[i]) != reference_fold(right[i]) {
                break;
            }
            i += 1;
        }
        if remaining < 0 {
            return 0;
        }
        reference_fold(left[i]) - reference_fold(right[i])
    }

    #[test]
    fn the_table_is_ascii_tolower_and_nothing_else() {
        for i in 0..256usize {
            assert_eq!(UPPER_TO_LOWER[i], reference_fold(i as u8) as u8, "byte {i:#04x}");
        }
        // The exact rows that pinned the identification.
        assert_eq!(UPPER_TO_LOWER[b'A' as usize], b'a');
        assert_eq!(UPPER_TO_LOWER[b'Z' as usize], b'z');
        assert_eq!(UPPER_TO_LOWER[b'a' as usize], b'a');
        assert_eq!(UPPER_TO_LOWER[b'@' as usize], b'@');
        assert_eq!(UPPER_TO_LOWER[b'[' as usize], b'[');
        assert_eq!(UPPER_TO_LOWER[0xc0], 0xc0, "no Latin-1 folding");
        assert_eq!(UPPER_TO_LOWER[0xff], 0xff);
    }

    /// SQL identifiers and keywords the engine actually compares.
    const WORDS: &[&[u8]] = &[
        b"\0",
        b"a\0",
        b"A\0",
        b"z\0",
        b"sqlite_master\0",
        b"SQLITE_MASTER\0",
        b"SQLite_Master\0",
        b"sqlite_temp_master\0",
        b"sqlite_stat1\0",
        b"BINARY\0",
        b"binary\0",
        b"RTRIM\0",
        b"nocase\0",
        b"NOCASE\0",
        b"[bracket]\0",
        b"{brace}\0",
        b"_underscore\0",
        b"ZZZ\0",
        b"zzz\0",
        b"zzzz\0",
    ];

    /// Pad so the "one byte past the right string's NUL" read stays in
    /// bounds (the `libc.rs` PAD precedent).
    fn padded(word: &[u8]) -> Vec<u8> {
        let mut buf = word.to_vec();
        buf.extend_from_slice(&[0u8; 8]);
        buf
    }

    #[test]
    fn icmp_matches_the_reference_on_every_pair() {
        for left in WORDS {
            for right in WORDS {
                let (l, r) = (padded(left), padded(right));
                assert_eq!(
                    unsafe { str_icmp(l.as_ptr(), r.as_ptr()) },
                    reference_icmp(&l, &r),
                    "{:?} vs {:?}",
                    core::str::from_utf8(left),
                    core::str::from_utf8(right)
                );
            }
        }
    }

    #[test]
    fn icmp_ignores_case_but_not_content() {
        let (a, b) = (padded(b"SELECT\0"), padded(b"select\0"));
        assert_eq!(unsafe { str_icmp(a.as_ptr(), b.as_ptr()) }, 0);

        let (a, b) = (padded(b"select\0"), padded(b"selecu\0"));
        assert_eq!(unsafe { str_icmp(a.as_ptr(), b.as_ptr()) }, -1);
        assert_eq!(unsafe { str_icmp(b.as_ptr(), a.as_ptr()) }, 1);
    }

    #[test]
    fn icmp_stops_on_the_left_terminator() {
        // A prefix compares as "less" by the difference of the folded
        // bytes, not by a normalized sign.
        let (a, b) = (padded(b"abc\0"), padded(b"abcd\0"));
        assert_eq!(unsafe { str_icmp(a.as_ptr(), b.as_ptr()) }, 0 - b'd' as i32);
        assert_eq!(unsafe { str_icmp(b.as_ptr(), a.as_ptr()) }, b'd' as i32);
    }

    #[test]
    fn the_result_is_a_raw_difference_of_folded_bytes() {
        let (a, b) = (padded(b"A\0"), padded(b"z\0"));
        assert_eq!(unsafe { str_icmp(a.as_ptr(), b.as_ptr()) }, b'a' as i32 - b'z' as i32);
        assert_eq!(unsafe { str_icmp(a.as_ptr(), b.as_ptr()) }, -25);
    }

    #[test]
    fn nicmp_matches_the_reference_across_every_budget() {
        for left in WORDS {
            for right in WORDS {
                let (l, r) = (padded(left), padded(right));
                for n in -2..=12i32 {
                    assert_eq!(
                        unsafe { str_nicmp(l.as_ptr(), r.as_ptr(), n) },
                        reference_nicmp(&l, &r, n),
                        "{:?} vs {:?} n={n}",
                        core::str::from_utf8(left),
                        core::str::from_utf8(right)
                    );
                }
            }
        }
    }

    #[test]
    fn a_non_positive_budget_compares_equal_without_reading() {
        // NULL pointers prove nothing is dereferenced.
        for n in [0i32, -1, -1000, i32::MIN + 1] {
            assert_eq!(
                unsafe { str_nicmp(core::ptr::null(), core::ptr::null(), n) },
                0,
                "n={n}"
            );
        }
    }

    #[test]
    fn the_lone_budget_that_still_compares_is_the_wrapping_one() {
        // `n = i32::MIN` breaks out of the loop immediately (it is
        // <= 0) but the pre-decrement wraps to `i32::MAX`, so the
        // "budget exhausted" test reads false and the difference is
        // computed after all. The original does exactly this
        // (`sub r2, r2, #1` does not saturate); reproduced, not fixed.
        let (a, b) = (padded(b"A\0"), padded(b"b\0"));
        assert_eq!(
            unsafe { str_nicmp(a.as_ptr(), b.as_ptr(), i32::MIN) },
            b'a' as i32 - b'b' as i32
        );
        assert_eq!(
            unsafe { str_nicmp(a.as_ptr(), b.as_ptr(), i32::MIN) },
            reference_nicmp(&a, &b, i32::MIN)
        );
    }

    #[test]
    fn nicmp_compares_only_the_prefix() {
        let (a, b) = (padded(b"sqlite_master\0"), padded(b"SQLITE_temp\0"));
        assert_eq!(unsafe { str_nicmp(a.as_ptr(), b.as_ptr(), 7) }, 0);
        assert_eq!(unsafe { str_nicmp(a.as_ptr(), b.as_ptr(), 8) }, b'm' as i32 - b't' as i32);
    }

    #[test]
    fn nicmp_stops_early_at_the_left_terminator() {
        // Budget larger than the string: the NUL ends it, and the
        // budget is still positive, so a real difference comes back.
        let (a, b) = (padded(b"ab\0"), padded(b"abcd\0"));
        assert_eq!(unsafe { str_nicmp(a.as_ptr(), b.as_ptr(), 10) }, 0 - b'c' as i32);
        // Exactly the string length: the budget runs out first.
        assert_eq!(unsafe { str_nicmp(a.as_ptr(), b.as_ptr(), 2) }, 0);
    }
}
