//! Ports of the ARM ADS 1.0.1 fixed-point hyperbolic-CORDIC libm kernels:
//!
//! - `log_atanh_kernel` — original: `FUN_08035b3c` @ 0x08035b3c (524 bytes).
//! - `exp_frac_kernel`  — original: `FUN_08035d50` @ 0x08035d50 (696 bytes).
//!
//! Both are digit-recurrence (CORDIC) engines over the SAME 42-word
//! Q30 atanh(2^-i) table, run for exactly 32 iterations with the classic
//! hyperbolic-convergence repeats at iterations 3 and 13 (where the
//! shift counters do not advance). All shifts follow ARM register-shift
//! semantics (low 8 bits; >= 32 fills with the sign bit) — the loop
//! counters push the shifts well past 31, so this is load-bearing.
//!
//! Data tables, extracted byte-exact from work/firmware/osos.dec
//! (file offset = load address - 0x08000000):
//! - [`ATANH_TABLE`]     @ 0x08986264 (log copy) and 0x0898642c (exp
//!   copy) — the two 168-byte blocks are byte-identical (verified), so
//!   one const serves both kernels.
//! - [`LOG_SEED_TABLE`]  @ 0x0898630c — 9 x 32-byte range-reduction rows
//!   for the log kernel (literal @ 0x08035d48 + pc @ 0x08035b90).
//! - [`EXP_SEED_TABLE`]  @ 0x089864d4 — 12 x 8-byte seed pairs for the
//!   exp kernel, indexed by -exponent-1 (literal @ 0x08036008 + pc
//!   @ 0x08035dc0, walked backwards).
//!
//! `log_atanh_kernel` (vectoring mode, sole caller `log_decompose`
//! @ 0x080340fc through the `LOG_ATANH_KERNEL` hook): computes
//! atanh(u) = ln(m) for the reduced u = (m^2-1)/(m^2+1), u a float bit
//! pattern in (2^-12, 0.6). Inputs <= 0x39800000 (2^-12, signed compare)
//! return unchanged. The seed row search (row 8 down to row 0; row 0
//! matches any u < 1, row 8 is unreachable because its exponent -14 is
//! below the domain floor) pre-rotates the state to
//! (x, y) ~ (A + u*B*2^-S, u*A + B*2^-S) in Q29 via 64-bit products
//! (`smull` + `__aeabi_lasr`), seeds the Q(30+scale-1) accumulator, then
//! 32 vectoring iterations drive y -> 0 while the accumulator gathers
//! signed atanh table terms. Result: `__fdiv(__i2f(acc),
//! __fscalb(__i2f(1 << (result_scale - 1)), 30))`.
//!
//! `exp_frac_kernel` (rotation mode, sole caller `expf_core`
//! @ 0x08033f40, call site 0x08033fdc, through the `EXP_FRAC_KERNEL`
//! hook): for frac a float bit pattern, writes sinh(frac) to
//! `*out_sinh`, cosh(frac) to `*out_cosh` and e^frac to `*out_result`
//! (the only output the caller reads). Inputs <= 0x39800000 short-cut to
//! (frac, 1.0f, `__fadd(frac, 1.0f)`). Otherwise the seed pair for the
//! exponent subtracts a running atanh sum from the Q29 mantissa to form
//! the residual angle z, a seed loop of `start_index` fixed rotations
//! rebuilds the matching (x, y), and 32 rotation iterations drive
//! z -> 0, converging (x, y) -> K*2^29*(cosh, sinh). The finale
//! multiplies by the inverse-gain constants 1/K * 2^-28 @ 0x08036010
//! (sinh) and 1/K * 2^-29 @ 0x08036014 (cosh, result), and rescales the
//! sinh output by subtracting `(adj + 1) << 23` from its exponent field
//! directly (adj = seed-loop left-shift debt).
//!
//! Deviations (behavior-preserving):
//! - The original stores the un-rescaled sinh product to `*out_sinh` and
//!   immediately overwrites it (str/sub/sub/str @ 0x08035fb8-0x08035fc4);
//!   only the final value is stored here.
//! - The original returns leftover registers (the popped frac/out_sinh
//!   pair); the caller ignores them, so the port returns nothing.
//! - The exponent >= 0 branch of `exp_frac_kernel` (frac >= 1.0) is
//!   unreachable from the sole caller (frac = x - floor(x) in [0, 1))
//!   but fully ported and pinned by tests.
//!
//! Every pinned test vector was generated by an independent Python
//! transcription of the disassembly (not this Rust) driving the
//! byte-exact tables. Measured accuracy vs the host libm across the
//! caller domains: atanh within 1 ulp; e^frac and cosh within 2 ulp,
//! sinh within 3 ulp (the sinh path rounds three times: __i2f, __fmul,
//! then the raw exponent-field rescale).

use crate::fp_fadd::__fadd;
use crate::fp_fconv::__i2f;
use crate::fp_fmuldiv::{__fdiv, __fmul};
use crate::fp_scalb::__fscalb;
use crate::runtime::aeabi_64shift::__aeabi_lasr;

/// 1.0f — the exp fast path's cosh output and addend.
const ONE_F: u32 = 0x3f80_0000;
/// 1/K * 2^-28 (K = hyperbolic CORDIC gain), float const @ 0x08036010:
/// the sinh output scale.
const SINH_SCALE: u32 = 0x319a_8f44;
/// 1/K * 2^-29, float const @ 0x08036014: the cosh / e^frac output scale.
const COSH_SCALE: u32 = 0x311a_8f44;

/// Shared Q30 atanh(2^-i) table, 42 words. Two byte-identical copies in
/// osos: @ 0x08986264 (log kernel) and @ 0x0898642c (exp kernel).
/// Entries 3/13 are repeated (the hyperbolic-convergence double
/// iterations) and the tail degenerates to 2^30 exactly once
/// atanh(2^-i) * 2^i rounds to 1.0 in Q30.
pub const ATANH_TABLE: [i32; 42] = [
    0x464fa9eb, 0x4162bbea, 0x40562472, 0x4015622b,
    0x4015622b, 0x40055622, 0x40015562, 0x40005556,
    0x40001555, 0x40000555, 0x40000155, 0x40000055,
    0x40000015, 0x40000005, 0x40000005, 0x40000001,
    0x40000000, 0x40000000, 0x40000000, 0x40000000,
    0x40000000, 0x40000000, 0x40000000, 0x40000000,
    0x40000000, 0x40000000, 0x40000000, 0x40000000,
    0x40000000, 0x40000000, 0x40000000, 0x40000000,
    0x40000000, 0x40000000, 0x40000000, 0x40000000,
    0x40000000, 0x40000000, 0x40000000, 0x40000000,
    0x40000000, 0x40000000,
];

/// One 32-byte range-reduction row of the log kernel's seed table.
/// A row matches u when `exp >= exponent(u)` and
/// `mant29(u) >> (exp - exponent(u)) < threshold`, i.e. when u is small
/// enough for the row's pre-rotation; rows are searched from 8 down to 0.
pub struct LogSeedEntry {
    /// Q29 acceptance bound on the row-aligned mantissa.
    pub threshold: i32,
    /// Largest input exponent the row serves.
    pub exp: i32,
    /// Q29 cosh-like pre-rotation coefficient (A).
    pub cosh_seed: i32,
    /// Q29 sinh-like pre-rotation coefficient (B, negative), applied as
    /// B * 2^-seed_shift.
    pub sinh_seed: i32,
    /// Binary point offset S of `sinh_seed`.
    pub seed_shift: i32,
    /// Initial atanh accumulator, in Q(30 + result_scale - 1).
    pub acc_seed: i32,
    /// Result fixed-point scale: acc is divided by 2^(30 + result_scale - 1).
    pub result_scale: i32,
    /// First CORDIC iteration index (into [`ATANH_TABLE`]).
    pub start_index: i32,
}

/// Log kernel seed table @ 0x0898630c, byte-exact (9 rows x 8 words).
/// Row 8 (exp -14) is unreachable — the fast path already consumed every
/// u <= 2^-12 — but is carried verbatim.
pub const LOG_SEED_TABLE: [LogSeedEntry; 9] = [
    LogSeedEntry { threshold: 0x20000000, exp: 0, cosh_seed: 0x20000000, sinh_seed: 0xe0000000_u32 as i32, seed_shift: 1, acc_seed: 0x2327d4f5, result_scale: 1, start_index: 1 },
    LogSeedEntry { threshold: 0x20000000, exp: -1, cosh_seed: 0x1c000000, sinh_seed: 0xe0000000_u32 as i32, seed_shift: 2, acc_seed: 0x259e4bf5, result_scale: 2, start_index: 2 },
    LogSeedEntry { threshold: 0x24924924, exp: -2, cosh_seed: 0x1b000000, sinh_seed: 0xdc000000_u32 as i32, seed_shift: 3, acc_seed: 0x2b1185b2, result_scale: 3, start_index: 3 },
    LogSeedEntry { threshold: 0x2aaaaaaa, exp: -3, cosh_seed: 0x1ab80000, sinh_seed: 0xd3000000_u32 as i32, seed_shift: 4, acc_seed: 0x36185a4e, result_scale: 4, start_index: 4 },
    LogSeedEntry { threshold: 0x35e50d79, exp: -4, cosh_seed: 0x1a8b0000, sinh_seed: 0xdb700000_u32 as i32, seed_shift: 5, acc_seed: 0x2c1b5271, result_scale: 5, start_index: 5 },
    LogSeedEntry { threshold: 0x2c145828, exp: -5, cosh_seed: 0x1a81dc00, sinh_seed: 0xebf60000_u32 as i32, seed_shift: 6, acc_seed: 0x18314ec1, result_scale: 6, start_index: 6 },
    LogSeedEntry { threshold: 0x30620a06, exp: -7, cosh_seed: 0x1a8067a1, sinh_seed: 0xe4de3940_u32 as i32, seed_shift: 8, acc_seed: 0x20c2e598, result_scale: 8, start_index: 8 },
    LogSeedEntry { threshold: 0x20c2da26, exp: -8, cosh_seed: 0x1a804c7f, sinh_seed: 0xfebd41c3_u32 as i32, seed_shift: 9, acc_seed: 0x0185b5dc, result_scale: 9, start_index: 9 },
    LogSeedEntry { threshold: 0x30b6bb7d, exp: -14, cosh_seed: 0x1a804814, sinh_seed: 0x065485dd, seed_shift: 13, acc_seed: 0xf85b392e_u32 as i32, result_scale: 13, start_index: 0 },
];

/// One seed pair of the exp kernel's table: the Q30-domain atanh sum
/// already "rotated away" for that input exponent, and the CORDIC
/// iteration index where the main loop picks up.
pub struct ExpSeed {
    /// Q29-mantissa-domain sum of the seed rotations' atanh terms,
    /// subtracted from mant29 to form the residual angle.
    pub atanh_sum: i32,
    /// Seed-rotation count = first main-loop iteration index.
    pub start_index: i32,
}

/// Exp kernel seed table @ 0x089864d4, byte-exact (12 pairs), indexed by
/// -exponent - 1 for exponents -1 down to -12 (the full main-path
/// domain: frac > 2^-12 and frac < 1 from the sole caller).
pub const EXP_SEED_TABLE: [ExpSeed; 12] = [
    ExpSeed { atanh_sum: 0x2327d4f5, start_index: 1 },
    ExpSeed { atanh_sum: 0x259e4bf6, start_index: 2 },
    ExpSeed { atanh_sum: 0x2b1185b2, start_index: 3 },
    ExpSeed { atanh_sum: 0x36185a4f, start_index: 4 },
    ExpSeed { atanh_sum: 0x2c1b5272, start_index: 5 },
    ExpSeed { atanh_sum: 0x18314ec2, start_index: 6 },
    ExpSeed { atanh_sum: 0x30629d83, start_index: 6 },
    ExpSeed { atanh_sum: 0x20c2e599, start_index: 8 },
    ExpSeed { atanh_sum: 0x0185b5dc, start_index: 9 },
    ExpSeed { atanh_sum: 0x030b6bb8, start_index: 9 },
    ExpSeed { atanh_sum: 0x0616d770, start_index: 9 },
    ExpSeed { atanh_sum: 0x0c2daee0, start_index: 9 },
];

/// ARM register-controlled ASR: only the low 8 bits of the shift count
/// participate, and counts >= 32 fill with the sign bit. The CORDIC
/// shift counters exceed 31 late in every 32-iteration run, so plain
/// Rust `>>` (UB/panic at 32) cannot be used.
#[inline]
fn arm_asr(value: i32, shift: i32) -> i32 {
    let s = (shift as u32) & 0xff;
    if s >= 32 {
        value >> 31
    } else {
        value >> s
    }
}

/// `i - (i >= 4) - (i >= 14)`: the effective shift index of CORDIC
/// iteration `i` once the repeated iterations 3 and 13 are discounted.
/// The original re-materializes this with cmp/movge chains at every use.
#[inline]
fn repeat_adjusted(i: i32) -> i32 {
    i - (i >= 4) as i32 - (i >= 14) as i32
}

/// log_atanh_kernel — original: `FUN_08035b3c` @ 0x08035b3c (524 bytes).
///
/// Fixed-point atanh: `u` is a float bit pattern, the result is
/// atanh(u) as a float bit pattern (see the module header). Inputs
/// <= 0x39800000 (2^-12; signed compare, so any negative bit pattern
/// too) return unchanged. Sole caller: `log_decompose` @ 0x080340fc via
/// the `LOG_ATANH_KERNEL` hook, which feeds u in [0, 0.6).
#[cfg_attr(target_os = "none", no_mangle)]
pub unsafe extern "C" fn log_atanh_kernel(u: u32) -> u32 {
    if (u as i32) <= 0x3980_0000 {
        return u;
    }
    let e = (((u << 1) >> 24) as i32).wrapping_sub(0x7f);
    // Q29 mantissa in [2^29, 2^30): implicit bit restored, << 6.
    let mant = (((u & 0x00ff_ffff) | 0x0080_0000) << 6) as i32;

    // Row search, 8 down to 0 (row 0 accepts everything below 1.0, so
    // the no-match defaults below are unreachable but kept faithful).
    let mut x: i32 = 0x2000_0000;
    let mut y: i32 = mant;
    let mut acc: i32 = 0;
    let mut scale_log2: i32 = 0;
    let mut i: i32 = 0;
    let mut min_shift: i32 = 0;
    for row in LOG_SEED_TABLE.iter().rev() {
        if row.exp >= e && row.threshold.wrapping_sub(arm_asr(mant, row.exp - e)) > 0 {
            // Pre-rotation in 64-bit Q58: x = A + u*B*2^-S,
            // y = u*A + B*2^-S, both taken >> 29 back to Q29. The lasr
            // shift splits differ so every operand stays in range.
            min_shift = if row.seed_shift > -e { -e } else { row.seed_shift };
            let x64 = (0x2000_0000i64 * row.cosh_seed as i64).wrapping_add(__aeabi_lasr(
                mant as i64 * row.sinh_seed as i64,
                (row.seed_shift - e) as u32,
            ));
            let y64 = __aeabi_lasr(
                mant as i64 * row.cosh_seed as i64,
                (-(e + min_shift)) as u32,
            )
            .wrapping_add(__aeabi_lasr(
                0x2000_0000i64 * row.sinh_seed as i64,
                (row.seed_shift - min_shift) as u32,
            ));
            x = (x64 >> 29) as i32;
            y = (y64 >> 29) as i32;
            acc = row.acc_seed;
            scale_log2 = row.result_scale - 1;
            i = row.start_index;
            break;
        }
    }

    // 32 vectoring iterations: drive y -> 0, gather atanh terms.
    let adj = repeat_adjusted(i);
    let mut sh_y = adj + min_shift + 1;
    let mut sh_x = adj - min_shift + 1;
    let mut sh_t = adj - scale_log2 + 1;
    for _ in 0..32 {
        // Reachable i stays within 0..=40 (start_index <= 9 + 31
        // iterations); the original indexes unchecked.
        let t = arm_asr(*ATANH_TABLE.get_unchecked(i as usize), sh_t);
        let dy = arm_asr(y, sh_y);
        let dx = arm_asr(x, sh_x);
        if y >= 0 {
            x = x.wrapping_sub(dy);
            acc = acc.wrapping_add(t);
            y = y.wrapping_sub(dx);
        } else {
            x = dy.wrapping_add(x);
            y = y.wrapping_add(dx);
            acc = acc.wrapping_sub(t);
        }
        if i != 3 && i != 13 {
            sh_y += 1;
            sh_x += 1;
            sh_t += 1;
        }
        i += 1;
    }

    // acc / 2^(30 + scale_log2), via __i2f / __fscalb / __fdiv exactly as
    // the original tail (scale_log2 <= 12, so 1 << scale_log2 is exact).
    let divisor = __fscalb(__i2f(1i32.wrapping_shl(scale_log2 as u32)), 30);
    __fdiv(__i2f(acc), divisor)
}

/// exp_frac_kernel — original: `FUN_08035d50` @ 0x08035d50 (696 bytes).
///
/// Fixed-point e^frac (see the module header): writes sinh(frac) /
/// cosh(frac) / e^frac float bit patterns through the three out
/// pointers; the sole caller (`expf_core` @ 0x08033f40 via the
/// `EXP_FRAC_KERNEL` hook) reads only `*out_result`. `frac` <= 2^-12
/// (signed compare) short-cuts to (frac, 1.0f, frac + 1.0f).
#[cfg_attr(target_os = "none", no_mangle)]
pub unsafe extern "C" fn exp_frac_kernel(
    frac: u32,
    out_sinh: *mut u32,
    out_cosh: *mut u32,
    out_result: *mut u32,
) {
    if (frac as i32) <= 0x3980_0000 {
        *out_sinh = frac;
        *out_cosh = ONE_F;
        *out_result = __fadd(frac, ONE_F);
        return;
    }
    let e = (((frac << 1) >> 24) as i32).wrapping_sub(0x7f);
    let mant = (((frac & 0x00ff_ffff) | 0x0080_0000) << 6) as i32;

    let mut x: i32 = 0x2000_0000;
    let mut y: i32 = 0;
    let n: i32;
    let mut z: i32;
    if e >= 0 {
        // Unreachable from the sole caller (frac < 1.0); kept faithful:
        // no seed subtraction, the raw Q29 mantissa is the angle.
        n = 0;
        z = mant;
    } else {
        // Exponent in [-12, -1] on the main path (the fast path consumed
        // everything below); the original indexes unchecked.
        let seed = EXP_SEED_TABLE.get_unchecked((-e - 1) as usize);
        n = seed.start_index;
        z = mant.wrapping_sub(seed.atanh_sum);
        // Align the residual to the main loop's fixed point.
        let s = repeat_adjusted(n) + e + 1;
        if s > 0 {
            z = z.wrapping_shl(s as u32);
        } else if s < 0 {
            z = arm_asr(z, -s);
        }
        // Seed rotations 0..n: fixed directions (negative at i = 0 and
        // i = 7, the (1 << i) & 0x81 test), y doubling each non-repeat
        // step to track the shrinking rotation scale.
        let mut shift: i32 = 1;
        for i in 0..n {
            let negative = (1i32.wrapping_shl(i as u32)) & 0x81 != 0;
            let dy = arm_asr(y, shift);
            let (xn, yn) = if negative {
                (dy.wrapping_add(x), y.wrapping_add(arm_asr(x, 1)))
            } else {
                (x.wrapping_sub(dy), y.wrapping_sub(arm_asr(x, 1)))
            };
            if i != 3 && i != 13 {
                shift += 2;
            }
            x = xn;
            y = yn.wrapping_shl((1 - (i == 3) as i32 - (i == 13) as i32) as u32);
        }
    }

    // 32 rotation iterations: drive z -> 0, (x, y) -> K*2^29*(cosh, sinh).
    let adj = repeat_adjusted(n);
    let mut sh_y = 2 * adj + 1;
    let mut sh_x = 1;
    let mut i = n;
    for _ in 0..32 {
        // Reachable i stays within 0..=40 (start_index <= 9 + 31).
        let mut t = *ATANH_TABLE.get_unchecked(i as usize);
        let z2 = if i == 3 || i == 13 {
            t = arm_asr(t, 1);
            z
        } else {
            z.wrapping_shl(1)
        };
        let dy = arm_asr(y, sh_y);
        let dx = arm_asr(x, sh_x);
        if z < 0 {
            x = x.wrapping_sub(dy);
            y = y.wrapping_sub(dx);
            z = z2.wrapping_add(t);
        } else {
            x = dy.wrapping_add(x);
            y = dx.wrapping_add(y);
            z = z2.wrapping_sub(t);
        }
        if i != 3 && i != 13 {
            sh_y += 1;
            sh_x += 1;
        }
        i += 1;
    }

    // Finale: inverse-gain multiplies; the sinh output's exponent field
    // is decremented by adj + 1 in raw bits (the seed loop's left-shift
    // debt), exactly as the original's sub/sub on the float pattern.
    let sinh_raw = __fmul(__i2f(y), SINH_SCALE);
    *out_sinh = sinh_raw
        .wrapping_sub((adj as u32) << 23)
        .wrapping_sub(0x0080_0000);
    *out_cosh = __fmul(__i2f(x), COSH_SCALE);
    *out_result = __fmul(__i2f(x.wrapping_add(arm_asr(y, adj))), COSH_SCALE);
}

#[cfg(test)]
mod tests {
    extern crate std;
    use super::*;

    /// Every pinned vector below was generated by an independent Python
    /// transcription of the osos disassembly (scratchpad sim.py) driving
    /// the byte-exact tables — not by this port.
    const LOG_PINS: &[(u32, u32)] = &[
        (0x3f000000, 0x3f0c9f54), // atanh(0.5)
        (0x3f19999a, 0x3f317219), // atanh(0.6)
        (0x3ecccccd, 0x3ed8e883),
        (0x3e99999a, 0x3e9e795b),
        (0x3e800000, 0x3e82c578),
        (0x3e4ccccd, 0x3e4f9920),
        (0x3dcccccd, 0x3dcd7c9f),
        (0x3d4ccccd, 0x3d4cf88e),
        (0x3ca3d70a, 0x3ca3dca2),
        (0x3c23d70a, 0x3c23d870),
        (0x3b449ba6, 0x3b449bcd),
        (0x3a83126f, 0x3a831272),
        (0x399d4952, 0x399d4953),
        (0x38d1b717, 0x38d1b717), // fast path (1e-4 < 2^-12)
        (0x39800001, 0x39800001), // just above the fast-path bound
    ];

    /// (frac, out_sinh, out_cosh, out_result) pins, same provenance.
    const EXP_PINS: &[(u32, u32, u32, u32)] = &[
        (0x3f7fffef, 0x3f966cf2, 0x3fc583a1, 0x402df849),
        (0x3f7d70a4, 0x3f947547, 0x3fc40519, 0x402c3d30),
        (0x3f666666, 0x3f8364e7, 0x3fb76f60, 0x401d6a23),
        (0x3f400000, 0x3f52835a, 0x3fa5b82f, 0x40077cee),
        (0x3f333333, 0x3f42328b, 0x3fa0a961, 0x4000e153),
        (0x3f000000, 0x3f056681, 0x3f90560c, 0x3fd3094e),
        (0x3ecccccd, 0x3ed24e22, 0x3f8a6095, 0x3fbef41e),
        (0x3e99999a, 0x3e9bea16, 0x3f85cda7, 0x3facc82d),
        (0x3e4ccccd, 0x3e4e2b08, 0x3f82918c, 0x3f9c56ed),
        (0x3dcccccd, 0x3dcd243b, 0x3f80a3fb, 0x3f8d763e),
        (0x3d4ccccd, 0x3d4ce2a7, 0x3f8028f8, 0x3f86900e),
        (0x3ca3d70a, 0x3ca3d9d6, 0x3f80068e, 0x3f8295f5),
        (0x3c23d70a, 0x3c23d7be, 0x3f8001a4, 0x3f814954),
        (0x3b449ba6, 0x3b449bba, 0x3f800026, 0x3f806274),
        (0x3a83126f, 0x3a831270, 0x3f800004, 0x3f8020c9),
        (0x399d4952, 0x399d4954, 0x3f800001, 0x3f8009d5),
        (0x39800001, 0x39800002, 0x3f800001, 0x3f800801),
        // Exponent >= 0 branch, unreachable from the caller but ported.
        (0x3f800000, 0x3f056681, 0x3f90560c, 0x3fd3094e),
        (0x3fc00000, 0x3f52835a, 0x3fa5b82f, 0x40077cee),
        (0x3fffffff, 0x3f966cfe, 0x3fc583aa, 0x402df854),
    ];

    fn atanh_kernel(u: u32) -> u32 {
        unsafe { log_atanh_kernel(u) }
    }

    fn exp_kernel(frac: u32) -> (u32, u32, u32) {
        let (mut s, mut c, mut r) = (0xdead_beef_u32, 0xdead_beef_u32, 0xdead_beef_u32);
        unsafe { exp_frac_kernel(frac, &mut s, &mut c, &mut r) };
        (s, c, r)
    }

    /// Host oracles through f64 (single final rounding to f32; see
    /// crate::libm::misc on why the f32 methods are avoided).
    fn host_atanh(u: f32) -> u32 {
        let v = (1.0 + u as f64) / (1.0 - u as f64);
        ((0.5 * v.ln()) as f32).to_bits()
    }

    fn ulp_distance(a: u32, b: u32) -> i64 {
        (a as i64 - b as i64).abs()
    }

    /// xorshift64* for reproducible random bit patterns (house pattern).
    struct Rng(u64);
    impl Rng {
        fn next(&mut self) -> u64 {
            let mut x = self.0;
            x ^= x >> 12;
            x ^= x << 25;
            x ^= x >> 27;
            self.0 = x;
            x.wrapping_mul(0x2545_f491_4f6c_dd1d)
        }
    }

    // ---- log_atanh_kernel ----

    #[test]
    fn log_kernel_pinned_vectors() {
        for &(u, want) in LOG_PINS {
            assert_eq!(atanh_kernel(u), want, "u={u:#010x}");
        }
    }

    #[test]
    fn log_kernel_fast_path_returns_input_unchanged() {
        // Signed compare: everything <= 0x39800000 (2^-12), including 0
        // and any negative bit pattern, passes through untouched.
        for u in [0, 1, 0x3980_0000, 0x8000_0000, 0xbf00_0000, 0xffff_ffff] {
            assert_eq!(atanh_kernel(u), u, "u={u:#010x}");
        }
    }

    #[test]
    fn log_kernel_matches_host_atanh_across_caller_domain() {
        // The sole caller feeds u = (m^2-1)/(m^2+1) in [0, 0.6); sweep the
        // whole reachable domain with random mantissas at every exponent.
        let mut rng = Rng(0xc0d1_c5ee_d5ee_d001);
        let mut checked = 0u32;
        for _ in 0..100_000 {
            let bits = ((rng.next() as u32) & 0x007f_ffff)
                | ((((rng.next() % 12) as u32 + 115) & 0xff) << 23);
            let u = f32::from_bits(bits);
            if !(f32::from_bits(0x3980_0000)..0.6).contains(&u) {
                continue;
            }
            let got = atanh_kernel(bits);
            let want = host_atanh(u);
            assert!(
                ulp_distance(got, want) <= 2,
                "u={u} bits={bits:#010x} got={got:#010x} want={want:#010x}"
            );
            checked += 1;
        }
        assert!(checked > 50_000);
    }

    // ---- exp_frac_kernel ----

    #[test]
    fn exp_kernel_pinned_vectors() {
        for &(frac, sinh, cosh, result) in EXP_PINS {
            let (s, c, r) = exp_kernel(frac);
            assert_eq!(s, sinh, "sinh frac={frac:#010x}");
            assert_eq!(c, cosh, "cosh frac={frac:#010x}");
            assert_eq!(r, result, "result frac={frac:#010x}");
        }
    }

    #[test]
    fn exp_kernel_fast_path() {
        // frac <= 2^-12: (frac, 1.0f, __fadd(frac, 1.0f)) — bit-exact
        // against the committed __fadd (which pins the ADS tie quirk).
        for frac in [0u32, 1, 0x3980_0000, 0x8000_0000, 0xb980_0000] {
            let (s, c, r) = exp_kernel(frac);
            assert_eq!(s, frac, "frac={frac:#010x}");
            assert_eq!(c, ONE_F, "frac={frac:#010x}");
            assert_eq!(r, unsafe { __fadd(frac, ONE_F) }, "frac={frac:#010x}");
        }
        assert_eq!(exp_kernel(0).2, ONE_F);
    }

    #[test]
    fn exp_kernel_matches_host_across_caller_domain() {
        // The sole caller feeds frac = x - floor(x) in [0, 1); sweep with
        // random mantissas at every reachable exponent (-12..=-1).
        let mut rng = Rng(0xe4bf_ac5e_ed00_d1c5);
        let mut checked = 0u32;
        for _ in 0..100_000 {
            let bits = ((rng.next() as u32) & 0x007f_ffff)
                | ((((rng.next() % 12) as u32 + 115) & 0xff) << 23);
            if bits <= 0x3980_0000 {
                continue;
            }
            let frac = f32::from_bits(bits) as f64;
            let (s, c, r) = exp_kernel(bits);
            assert!(
                ulp_distance(r, (frac.exp() as f32).to_bits()) <= 2,
                "exp frac={frac} bits={bits:#010x} r={r:#010x}"
            );
            assert!(
                ulp_distance(s, (frac.sinh() as f32).to_bits()) <= 3,
                "sinh frac={frac} bits={bits:#010x} s={s:#010x}"
            );
            assert!(
                ulp_distance(c, (frac.cosh() as f32).to_bits()) <= 2,
                "cosh frac={frac} bits={bits:#010x} c={c:#010x}"
            );
            checked += 1;
        }
        assert!(checked > 50_000);
    }
}
